<?php
namespace common\traits;

use common\essence\Genre;
use common\essence\ImageUploader;

trait ImageUploaderTrait
{
    public function saveImage($fileName)
    {
        $this->image= $fileName;
        return $this->save(false);
    }
    public function getImage()
    {
        return ($this->image) ? '/uploads/'. $this->image : '/uploads/no-image.png';
    }
    private function deleteImage()
    {
        $imageModel = new ImageUploader();
        $imageModel->deleteImage($this->image);
    }
    public function beforeDelete()
    {
        $this->deleteImage();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }


}